### ISSUE TITLE
List is going out of range when user types anything except 0,1 and 2 

### ISSUE THREAD

**Issue by LastDeadlock** [LastDeadlock/hacktoberfest#1]
this will not take to much to debug the code but it's important because if you put 3,4,53434 etc when program asked user to enter the value it extended  the range as it goes out of the list index number.

**Comment by DerMoehre** [comment]
Hi, is this still open? 
I would like to help you with this, but i am not that experienced in coding

**Comment by DerMoehre** [comment]
Okay, I will have a Look at the File and add a PR when I am ready :-)

**Comment by LastDeadlock** [comment]
sure thing.

**Comment by LastDeadlock** [comment]
sure thing.

**Comment by DerMoehre** [comment]
Added PR#2 regarding this issue :)

**Comment by LastDeadlock** [comment]
thank you for adding while loop now i'm closing this issue
